name: velopay
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.6
  pin_code_fields: ^8.0.1
  intl: ^0.19.0
  flutter_launcher_icons: ^0.9.2  # Add this dependency for app icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^1.0.3

flutter:
  assets:
    - images/sp1.jpg
    - images/sp2.jpg
    - images/pas.jpg
    - images/mtn.png
    - images/glo.png
    - images/9mobile.jpg
    - images/airtel.jpg
    - images/finger.jpg

  uses-material-design: true

# flutter_launcher_icons configuration outside the flutter section
flutter_icons:
  android: true
  ios: true
  image_path: "images/VP.png"  # Path to your app icon image
